### ISSUE TITLE
orgbabelhelper 

### ISSUE THREAD

**Issue by yssource** [dfeich/org-babel-examples#2]
It would be very great appreciated for you, if it's going to upgrade **orgbabelhelper** to work with python3x.

**Comment by dfeich** [comment]
Hi yssource

I'll make an effort about it. I still must do the migration to python3 myself and get a bit acquainted with it. With python 2.x there were lots of headaches about unicode problems with babel. I expect all of these to go away at once in python 3. Maybe I have some time this week.

Best regards,
Derek

**Comment by lazysquid** [comment]
It would be nice if **orgbabelhelper** support python3.x.
Also, have you ever consider uploading **orgbabelhelper** to pip2/pip3 repository?
If it supports pip, it will be much easier to use.

**Comment by dfeich** [comment]
Ok. I now created a first version of the new orgbabelhelper library for python3. It again gets created from within the respective example document. I already uploaded it also to anaconda.org:

https://anaconda.org/dfeich/orgbabelhelper

I will also upload to pip. Should be straightforward.
I would be very glad if you could give me feedback after testing.

Best regards,
Derek

**Comment by lazysquid** [comment]
@dfeich Currently I removed conda in my system and can't install it now because of my project.  
Let me know when you upload it to pip.
I'll test it after that.

**Comment by dfeich** [comment]
Hi
I just uploaded to PyPi. Seems like it takes a bit until the package becomes visible. Upload went ok and repeated upload yields "file exists". I have not tried this package yet... am a bit under a heavy workload. So, please tell me whether it works for you.

**Comment by yssource** [comment]
pip python3 works for me.
Thanks.
