### ISSUE TITLE
documentation has dead links

### ISSUE THREAD

**Issue by notuntoward** [dfeich/org-babel-examples#8]
Just thought I'd let you know that the documentation has quite a few dead links.  For example, in Section 4 of the [IPython section](https://github.com/dfeich/org-babel-examples/blob/master/python/ipython-babel.org), the link to the .png file is 404.

**Comment by dfeich** [comment]
Thanks for reporting this. I have not used ob-ipython in some time (mostly, I am just using the standard python babel). I started updating.

**Comment by dfeich** [comment]
Hi

After having a deeper look at the state of ob-ipython, I think the project has been mostly abandoned. There are numerous bug reports and pull requests with no response from the author. I started to test another implementation for jupyter which looked very promising to me (and to many others). Please try https://github.com/dzop/emacs-jupyter. I do not yet have an example file in this collection... maybe this something to test out over Xmas.

I think I will decommission the ob-ipython example.

**Comment by notuntoward** [comment]
OK, thanks.  I'll take a look at emacs-jupyter, then.
